sudo: required
services:
  - docker

before_install:
  - docker build -t lucadefra92/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucadefra92/react-test npm test

after_success:
  - docker build -t lucadefra92/multi-client ./client
  - docker build -t lucadefra92/multi-nginx ./nginx
  - docker build -t lucadefra92/multi-server ./server
  - docker build -t lucadefra92/multi-worker ./worker

