sudo: required
services:
  - docker

before_install:
  - docker build -t lucadefra92/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lucadefra92/react-test npm test

after_success:
  - docker build -t lucadefra92/multi-client ./client
  - docker build -t lucadefra92/multi-nginx ./nginx
  - docker build -t lucadefra92/multi-server ./server
  - docker build -t lucadefra92/multi-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and push them to docker hum
  - docker push lucadefra92/multi-client
  - docker push lucadefra92/multi-nginx
  - docker push lucadefra92/multi-server
  - docker push lucadefra92/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-108156832047
  bucket_path: docker-multi
  on:
    branch: master
